# Dockerfile — super simple, debug-ready version
FROM golang:1.23-alpine AS builder


RUN apk add --no-cache git

WORKDIR /app
COPY go.mod .
COPY main.go .

RUN go mod download && go mod verify
RUN go install github.com/go-delve/delve/cmd/dlv@latest

# disable compiler optimization
RUN go build -gcflags="all=-N -l" -o server .

FROM alpine:latest
RUN apk add --no-cache ca-certificates

COPY --from=builder /go/bin/dlv /
COPY --from=builder /app/server /

# server (app)
EXPOSE 8080
# delve 
EXPOSE 2345 


# delve in headless-mode
CMD ["/dlv", "--listen=:2345", "--headless=true", "--api-version=2", \
     "--accept-multiclient", "--log", "--continue-on-start", \
     "exec", "/server", "--", "-addr=0.0.0.0:8080"]